import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'
import { Providers } from '../components/providers'
import { ThemeProvider } from 'next-themes'

import Script from 'next/script'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Script src="https://example.com/script.js" strategy="lazyOnload" />
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          value={{ light: 'light', dark: 'dark' }}
        >
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  )
}
